client: Switch from jQuery.ajax to fetch
SSilence/selfoss pull request #1215
Opened 2020-08-28 06:57 UTC by jtojnar

This will bring us one step closer to removing jQuery.

Unfortunately the native promises lack built-in support for aborting so we need to somewhat clumsily return `AbortController` alongside them.

While at it, I also got rid of the jQuery Deferreds so the only remaining use of jQuery is the DOM manipulation. Hopefully, it will not remain for long.

2020-09-02 22:23 UTC, jtojnar commented
@niol will you be available to review this some time? I can also guide you through the Parcel-based build from #1137 if you need to bring up to speed.

2020-09-04 11:07 UTC, niol reviewed
I cannot add a source.

2020-09-04 11:07 UTC, niol commented on assets/js/selfoss-db.js
> +            selfoss.activeAjaxReq.controller.abort();
This triggers everytime `reloadList` gets called.

2020-09-04 11:25 UTC, jtojnar commented on assets/js/selfoss-db.js
> +            selfoss.activeAjaxReq.controller.abort();
Hmm, looks like `liftToPromiseField` does not quite work after the latest refactoring. It drops the `controller` field from the object:

```
> selfoss.ajax.get('sources')
Object { promise: Promise { "pending" } }

> selfoss.ajax.fetch('sources')
Object { controller: AbortController, promise: Promise { "pending" } }
```

2020-09-04 12:17 UTC, jtojnar commented on assets/js/selfoss-db.js
> +            selfoss.activeAjaxReq.controller.abort();
Looks like it was actually caused by the functions from `fetch-friends` library. Not exactly sure why, but I created our own `selfoss.ajax.option` function and it seems to work.

2020-09-04 12:25 UTC, jtojnar commented
Thanks for checking it out. It should be fixed now.

The _add source_ button not functioning was caused by forgetting to call `.text()` on the `fetch`’s `Response`. I checked the rest of the code and found only two other places where we expect HTML instead of JSON and those called it correctly. Hopefully, I did not miss any.

I also had to fix the `Sources\Write` controller to handle missing `tags` field since the new field does not send it when there are no tags.

2020-09-05 14:44 UTC, niol commented
With offline storage enabled, the client does not chain load items and stops after `items_perpage`.

2020-09-05 15:21 UTC, niol commented
An then it seems to load the same entries over and over again.

2020-09-05 15:23 UTC, niol commented
I I shut down the server, it keeps the ajax requests unfinished although the "Connection refused" should terminate them immediately.

2020-09-05 15:37 UTC, jtojnar commented
If I manually trigger `selfoss.dbOffline.sendNewStatuses()`, it seems to fetch another page. I am not sure what is supposed to trigger the fetch of the next page.

2020-09-05 15:40 UTC, niol commented
when `selfoss.dbOffline.newerEntriesMissing` is true.

2020-09-05 15:51 UTC, jtojnar commented
That seems to be true here but no luck.

2020-09-05 16:38 UTC, niol commented
I would try the following but I'm stuck with a bundler error.

```diff
--- a/assets/js/selfoss-db.js
+++ b/assets/js/selfoss-db.js
@@ -157,16 +157,19 @@ selfoss.dbOnline = {
                     selfoss.dbOffline.storeEntries(data.newItems)
                         .then(function() {
                             selfoss.dbOffline.storeLastUpdate(dataDate);
-
                             selfoss.dbOnline._syncDone();
-
-                            // fetch more if server has more
-                            if (selfoss.dbOffline.newerEntriesMissing) {
-                                selfoss.dbOnline.sync();
-                            }
                         });
                 }
 
+                if (selfoss.dbOffline.newerEntriesMissing
+                    || selfoss.dbOffline.needsSync) {
+                    // There are still new items to fetch
+                    // or statuses to send
+                    syncing.request.promise.then(function () {
+                        selfoss.dbOffline.sendNewStatuses();
+                    });
+                }
+
                 if ('itemUpdates' in data) {
                     // refresh entry statuses in db and dequeue queued
                     // statuses but do not calculate stats as they are taken
```

2020-09-06 01:08 UTC, jtojnar commented
Yeah, the bundlers are somewhat finicky in my experience. If I do `git rebase` with `npm run dev` running it breaks horribly, and I need to delete `assets/.cache` and restart it. OR sometimes on a syntax error, it is just swallowed and I need to restart it to see the error message. Unfortunately, when I tried Webpack it did not seem much better.

That seems to work with a minor tweak:

```patch
--- a/assets/js/selfoss-db.js
+++ b/assets/js/selfoss-db.js
@@ -159,14 +159,18 @@ selfoss.dbOnline = {
                             selfoss.dbOffline.storeLastUpdate(dataDate);
 
                             selfoss.dbOnline._syncDone();
-
-                            // fetch more if server has more
-                            if (selfoss.dbOffline.newerEntriesMissing) {
-                                selfoss.dbOnline.sync();
-                            }
                         });
                 }
 
+                if (selfoss.dbOffline.newerEntriesMissing
+                    || selfoss.dbOffline.needsSync) {
+                    // There are still new items to fetch
+                    // or statuses to send
+                    selfoss.dbOnline.syncing.request.promise.then(function () {
+                        selfoss.dbOffline.sendNewStatuses();
+                    });
+                }
+
                 if ('itemUpdates' in data) {
                     // refresh entry statuses in db and dequeue queued
                     // statuses but do not calculate stats as they are taken
```

Thanks.

2020-09-06 03:35 UTC, jtojnar commented
But that patch triggers a sync loop you mention, the last page does not seem to get picked up.

2020-09-07 10:54 UTC, niol commented
The sync loop seems to be specific to sqlite and how we compare dates as simple strings.

We should either use specific syntax for sqlite queries or ensure compared dates share the same timezone.

For instance, the following seems to be fixing the problem.
```diff
--- a/src/controllers/Items/Sync.php
+++ b/src/controllers/Items/Sync.php
@@ -56,11 +56,12 @@ class Sync {
         }

         $since = new \DateTime($params['since']);
+        $since->setTimeZone(new \DateTimeZone(date_default_timezone_get()));

         $last_update = new \DateTime($this->itemsDao->lastUpdate());

         $sync = [
-            'lastUpdate' => $last_update->format('Y-m-d H:i:s'),
+            'lastUpdate' => $last_update->format(\DateTime::ATOM),
         ];

         $sinceId = 0;
@@ -73,6 +74,7 @@ class Sync {
                     // only send 1 day worth of items
                     $notBefore = new \DateTime();
                     $notBefore->sub(new \DateInterval('P1D'));
+                    $notBefore->->setTimeZone(new \DateTimeZone(date_default_timezone_get()));
                 }

                 $itemsHowMany = $f3->get('items_perpage');
```

2020-09-11 12:17 UTC, niol requested changes

2020-09-11 13:57 UTC, merged